// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Command is an autogenerated mock type for the Command type
type Command struct {
	mock.Mock
}

// AlterTable provides a mock function with given fields: name, commands
func (_m *Command) AlterTable(name string, commands string) error {
	ret := _m.Called(name, commands)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(name, commands)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateTable provides a mock function with given fields: name, columns
func (_m *Command) CreateTable(name string, columns string) error {
	ret := _m.Called(name, columns)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(name, columns)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Execute provides a mock function with given fields: queryCommand
func (_m *Command) Execute(queryCommand string) error {
	ret := _m.Called(queryCommand)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(queryCommand)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
