// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	entity "active-order-management/domain/entity"

	mock "github.com/stretchr/testify/mock"
)

// Migration is an autogenerated mock type for the Migration type
type Migration struct {
	mock.Mock
}

// Apply provides a mock function with given fields: migrations
func (_m *Migration) Apply(migrations []entity.Migration) {
	_m.Called(migrations)
}
